services:
  - type: web
    name: my-api
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:migrate RAILS_ENV=production
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
