default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_api_development
  username: myapp
  password: 24Feb1985
  host: localhost
  port: 5432

test:
  <<: *default
  database: movie_api_test

production:
  <<: *default
  # database: movie_api_db_a2dq
  # username: movie_api_db_a2dq_user
  # password: <%= ENV["DB_PASSWORD"] %>
  # host: dpg-cv54dcvnoe9s73edl9g0-a.oregon-postgres.render.com
  # port: 5432
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sslmode: require
