
default: &default
  adapter: postgresql
  encoding: unicode
  username: myapp
  password: let me in  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: movies_api_development  
  username: myapp
  password: let me in
  host: 127.0.0.1
  port: 5432

  # Do not set this db to the same as development or production.
  test:
  <<: *default
  database: movies_api_test


production:
  primary: &primary_production
    <<: *default
    database: movies_api_production
    username: myapi
    password: let me in
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>

  