default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_api_development
  username: myapp
  password: 24Feb1985
  host: localhost
  port: 5432

test:
  <<: *default
  database: movie_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "DATABASE_URL_NOT_SET" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
